# Generated by Django 5.0.1 on 2024-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=120)),
                ('SubjectCode', models.CharField(max_length=120)),
                ('Credit', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='Subjects',
            field=models.ManyToManyField(to='myApp.subjectmodel'),
        ),
    ]
