# Generated by Django 5.0.1 on 2024-01-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_customuser_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='addJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=120)),
                ('Job_Description', models.CharField(max_length=500)),
                ('Job_Requirements', models.CharField(max_length=500)),
            ],
        ),
    ]
