# Generated by Django 5.0.1 on 2024-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_jobapplymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='maximumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Second_Number', models.CharField(blank=True, max_length=255, null=True)),
                ('Third_Number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
